title:  Setup Canon printer on MAC | Canon.com/ijsetup 
description: Visit ij.start.canon and get canon printer driver software on your device. Follow the procedure to setup canon printer and connect with the wireless network.
